### PR TITLE
default High-Gain Mode high for Hamamatsu InGaAs

### PR DESCRIPTION
**Pull request by mzieg**
Hi Trent, I haven't checked WPSC, but if you're not setting this explicitly, this would generate a change in performance for InGaAs and Andor units.

Edit: or would, if WasatchNET supported high-gain on Andor...

### CODE REVIEW

**Comment by trestoh** [comment]
> Hi Trent, I haven't checked WPSC, but if you're not setting this explicitly, this would generate a change in performance for InGaAs and Andor units.
> 
> Edit: or would, if WasatchNET supported high-gain on Andor...

Mark, what does this default to on at the hardware level? It does not appear that WPSC sets this explicitly unless requested. I'm wondering if we might want to track this on a per measurement level.

**Comment by trestoh** [comment]
And what is the motivation here? I'm okay with approving if I know the why

**Comment by mzieg** [comment]
> > Hi Trent, I haven't checked WPSC, but if you're not setting this explicitly, this would generate a change in performance for InGaAs and Andor units.
> > Edit: or would, if WasatchNET supported high-gain on Andor...
> 
> Mark, what does this default to on at the hardware level? 

I *think* it defaults off.  I'll have access to a test unit Monday to confirm.

> we might want to track this on a per measurement level.

That's a good idea.  We don't currently include this in ENLIGHTEN measurement metadata.

**Comment by mzieg** [comment]
> > Mark, what does this default to on at the hardware level?
> I _think_ it defaults off. I'll have access to a test unit Monday to confirm.
It defaults on.  So this is simply changing an "implicit" setting to "explicit" (which I think is preferable and more readable to users).
> > we might want to track this on a per measurement level.
> That's a good idea. We don't currently include this in ENLIGHTEN measurement metadata.

I've added that to ENLIGHTEN:
https://github.com/WasatchPhotonics/ENLIGHTEN/pull/85

I think the relevant WPSC code would be in WPProduction, and I'm not going to dive in there at this time.

**Comment by mzieg** [comment]
Screenshot 2022-12-19 at 12 23 25 PM
Screenshot 2022-12-19 at 12 23 29 PM

**Pull request merged**
